config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: change-doc
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-bistre-blue.sh
        container: qc.acc_nerdy-fuchsia-woodpecker
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-celadon-stingray.sh
        container: qc.doc_wheezy-heliotrope-guppy
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-tan-pig.sh
        container: qc.doc_hasty-saffron-mouse
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-harlequin-snake.sh
        container: qc.doc_freaky-amber-pinscher
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-coral-fowl.sh
        container: qc.lic_grumpy-apricot-dollar
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-bistre-earwig.sh
        container: qc.sec_trippy-apricot-caiman
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-pink-lynx.sh
        container: qc.sec_scaly-periwinkle-barracuda
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-tangerine-whippet.sh
        container: qc.sty_fuzzy-chartreuse-russel
      github.com/grycap/oscar hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-pear-crane.sh
        container: qc.sty_skinny-saffron-tamarin
      github.com/grycap/oscar jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-bistre-zebra.sh
        container: qc.sty_sleazy-aquamarine-lobster
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-mustard-frog.sh
        container: qc.sty_muggy-magnolia-hare
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-ruby-orangutan.sh
        container: qc.ver_gimpy-amaranth-mole
timeout: 1800
