config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/gosec
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: master
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-beige-whippet.sh
        container: qc.acc_chummy-cinnamon-quoll
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-amaranth-malamute.sh
        container: qc.doc_boozy-cerulean-macaque
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-celadon-panda.sh
        container: qc.doc_gamy-eggplant-gerbil
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-lavender-hedgehog.sh
        container: qc.doc_cranky-maroon-birman
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-violet-zebu.sh
        container: qc.lic_skinny-buff-chimpanzee
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-asparagus-hyrax.sh
        container: qc.sec_lanky-harlequin-catfish
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-viridian-impala.sh
        container: qc.sec_sloppy-xanthic-spitz
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-rose-tetra.sh
        container: qc.sty_cozy-purple-coati
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-copper-crane.sh
        container: qc.ver_wheezy-maroon-bloodhound
timeout: 1800
