config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.2
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: master
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-cinnabar-fousek.sh
        container: qc.acc_chummy-black-koala
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-corn-saola.sh
        container: qc.doc_shabby-champagne-jaguar
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-scarlet-mammoth.sh
        container: qc.doc_grumpy-sepia-yak
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.silly-asparagus-gerbil.sh
        container: qc.doc_clammy-brown-yak
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-bistre-gecko.sh
        container: qc.lic_sleepy-amber-barb
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-eggplant-dunker.sh
        container: qc.sec_hasty-olivine-rat
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-wisteria-iguana.sh
        container: qc.sec_surly-cornflower-bat
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-coral-newt.sh
        container: qc.sty_sunny-taupe-cassowary
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-saffron-sheepdog.sh
        container: qc.sty_pasty-gold-goat
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-taupe-centipede.sh
        container: qc.ver_trippy-burgundy-seahorse
timeout: 1800
