config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: change-doc
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-asparagus-warthog.sh
        container: qc.acc_geeky-cardinal-dog
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-chestnut-bee.sh
        container: qc.doc_tasty-pear-ocelot
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-russet-bandicoot.sh
        container: qc.doc_woolly-yellow-quoll
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-malachite-fish.sh
        container: qc.doc_lumpy-purple-giraffe
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-linen-macaque.sh
        container: qc.lic_tacky-auburn-eagle
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.beady-burgundy-eagle.sh
        container: qc.sec_shaggy-brown-yak
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-cobalt-angelfish.sh
        container: qc.sec_messy-green-akbash
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-lemon-butterfly.sh
        container: qc.sty_snoopy-smalt-numbat
      github.com/grycap/oscar hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-sepia-duck.sh
        container: qc.sty_skinny-malachite-toad
      github.com/grycap/oscar jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-scarlet-civet.sh
        container: qc.sty_cranky-goldenrod-toad
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-thistle-wolfhound.sh
        container: qc.sty_fuzzy-peach-meerkat
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-harlequin-quail.sh
        container: qc.ver_cranky-celadon-walrus
timeout: 1800
