config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/gosec
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: master
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-vermilion-iguana.sh
        container: qc.acc_queasy-salmon-chameleon
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.silly-persimmon-ostrich.sh
        container: qc.doc_sleepy-vermilion-numbat
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-vermilion-tiger.sh
        container: qc.doc_shaggy-seashell-akita
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-blue-bee.sh
        container: qc.doc_wheezy-heliotrope-lizard
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.beady-fuchsia-hamster.sh
        container: qc.lic_goopy-myrtle-birman
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-asparagus-mau.sh
        container: qc.sec_bluesy-yellow-walrus
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-beige-dunker.sh
        container: qc.sec_chewy-tangerine-flamingo
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-heliotrope-moose.sh
        container: qc.sty_nerdy-yellow-eleuth
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-thistle-chinchilla.sh
        container: qc.ver_ugly-tomato-tarantula
timeout: 1800
