config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: change-doc
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-taupe-uguisu.sh
        container: qc.acc_baggy-salmon-havanese
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-grey-fousek.sh
        container: qc.doc_homey-razzmatazz-forest
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-brown-jackal.sh
        container: qc.doc_frumpy-blue-javanese
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.beady-white-eagle.sh
        container: qc.doc_flimsy-tan-tapir
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-yellow-reindeer.sh
        container: qc.lic_nerdy-white-schnauzer
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-cinnamon-rat.sh
        container: qc.sec_lovely-mauve-dane
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-cerulean-molly.sh
        container: qc.sec_surly-magnolia-bulldog
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-beige-ray.sh
        container: qc.sty_pasty-olive-ray
      github.com/grycap/oscar hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-azure-baboon.sh
        container: qc.sty_snazzy-seashell-spider
      github.com/grycap/oscar jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-scarlet-dane.sh
        container: qc.sty_skimpy-cinnabar-hyrax
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-periwinkle-worm.sh
        container: qc.sty_grumpy-yellow-dollar
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-orange-sloth.sh
        container: qc.ver_squeaky-copper-hamster
timeout: 1800
