config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: master
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-persimmon-monster.sh
        container: qc.acc_craggy-razzmatazz-capuchin
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-malachite-salamander.sh
        container: qc.doc_pretty-chartreuse-eel
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-amaranth-jellyfish.sh
        container: qc.doc_seedy-magnolia-russel
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-heliotrope-caracal.sh
        container: qc.doc_queasy-sepia-magpie
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-platinum-bullfrog.sh
        container: qc.lic_muzzy-rose-oriole
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-bistre-angora.sh
        container: qc.sec_hilly-emerald-eleuth
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-black-sheepdog.sh
        container: qc.sec_gamy-smalt-mammoth
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-celadon-ragdoll.sh
        container: qc.sty_pretty-sangria-weasel
      github.com/grycap/oscar hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-eggplant-monkey.sh
        container: qc.sty_smelly-myrtle-gharial
      github.com/grycap/oscar jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-cerise-impala.sh
        container: qc.sty_baggy-champagne-kudu
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-lavender-booby.sh
        container: qc.sty_cheeky-charcoal-donkey
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-beige-tang.sh
        container: qc.ver_woozy-tangerine-cow
timeout: 1800
