config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/gosec
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: master
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-saffron-elephant.sh
        container: qc.acc_stinky-maroon-spider
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-carmine-anteater.sh
        container: qc.doc_cheeky-amethyst-beagle
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-salmon-tamarin.sh
        container: qc.doc_crabby-ultramarine-paradise
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-carmine-sparrow.sh
        container: qc.doc_snippy-corn-maltese
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-coral-loon.sh
        container: qc.lic_slimy-smalt-burmese
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-lilac-lizard.sh
        container: qc.sec_droopy-cream-loon
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-lemon-tiger.sh
        container: qc.sec_freaky-vermilion-chinook
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-cinnabar-chicken.sh
        container: qc.sty_sunny-orange-hamster
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-scarlet-gopher.sh
        container: qc.ver_frumpy-magenta-gopher
timeout: 1800
