config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: change-doc
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.surly-gamboge-dachsbracke.sh
        container: qc.acc_squirrely-chestnut-zorse
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.ready-corn-capuchin.sh
        container: qc.doc_scummy-orchid-chicken
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-razzmatazz-hamster.sh
        container: qc.doc_snoopy-rose-baboon
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-myrtle-robin.sh
        container: qc.doc_hilly-salmon-quokka
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-cyan-dog.sh
        container: qc.lic_stinky-lime-lion
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-green-fish.sh
        container: qc.sec_paltry-brass-argentino
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.messy-rose-iguana.sh
        container: qc.sec_flabby-purple-duck
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-charcoal-turkey.sh
        container: qc.sty_stuffy-lime-bear
      github.com/grycap/oscar hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-seashell-javanese.sh
        container: qc.sty_snappy-beige-saola
      github.com/grycap/oscar jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-myrtle-spoonbill.sh
        container: qc.sty_gummy-khaki-rottweiler
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-firebrick-antelope.sh
        container: qc.sty_shabby-wheat-dodo
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-gamboge-fish.sh
        container: qc.ver_skimpy-firebrick-stingray
timeout: 1800
