config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: change-doc
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-rose-caiman.sh
        container: qc.acc_shaky-periwinkle-tiger
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-blue-crocodile.sh
        container: qc.doc_snippy-jade-mandrill
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-lime-kakapo.sh
        container: qc.doc_droopy-gamboge-serval
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-wisteria-grouse.sh
        container: qc.doc_lovely-razzmatazz-sponge
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.homely-red-spitz.sh
        container: qc.lic_woozy-rose-slug
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-carmine-scorpion.sh
        container: qc.sec_snazzy-asparagus-reindeer
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-peach-walrus.sh
        container: qc.sec_squirrely-cyan-barnacle
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-tomato-chinook.sh
        container: qc.sty_stinky-cerise-moth
      github.com/grycap/oscar hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-auburn-cattle.sh
        container: qc.sty_whiny-rust-emu
      github.com/grycap/oscar jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-wheat-chamois.sh
        container: qc.sty_scaly-tan-dog
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-cardinal-blue.sh
        container: qc.sty_leaky-emerald-dugong
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-cinnamon-moth.sh
        container: qc.ver_pretty-persimmon-avocet
timeout: 1800
