config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: master
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-amethyst-dragon.sh
        container: qc.acc_wimpy-burgundy-bordeaux
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-tangerine-vole.sh
        container: qc.doc_gamy-silver-dachshund
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-heliotrope-moorhen.sh
        container: qc.doc_hazy-lemon-owl
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-heliotrope-corgi.sh
        container: qc.doc_shabby-asparagus-malamute
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-periwinkle-snake.sh
        container: qc.lic_grumpy-ruby-dingo
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-indigo-squirt.sh
        container: qc.sec_beady-black-lionfish
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-crimson-indri.sh
        container: qc.sty_squirrely-gamboge-coral
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-chartreuse-vulture.sh
        container: qc.ver_scaly-cinnabar-sparrow
timeout: 1800
