config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.6
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: change-doc
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-heliotrope-jellyfish.sh
        container: qc.acc_geeky-taupe-yak
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-silver-walrus.sh
        container: qc.doc_tacky-ultramarine-dachsbracke
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-ruby-lobster.sh
        container: qc.doc_queasy-cinnabar-dingo
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-wheat-abyssinian.sh
        container: qc.doc_woolly-cyan-sloth
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-cinnabar-sheepdog.sh
        container: qc.lic_silly-lime-saola
  QC.Met:
    repos:
      github.com/grycap/oscar validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-gold-mole.sh
        container: qc.met_seedy-sangria-akita
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-magenta-bat.sh
        container: qc.sec_muggy-cerulean-capybara
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-indigo-wolf.sh
        container: qc.sec_flaky-sangria-coati
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.messy-amaranth-wombat.sh
        container: qc.sty_scaly-purple-zebu
      github.com/grycap/oscar hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-gold-buzzard.sh
        container: qc.sty_fuzzy-eggplant-cheetah
      github.com/grycap/oscar jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-amber-bison.sh
        container: qc.sty_frumpy-linen-cougar
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-magnolia-robin.sh
        container: qc.sty_skimpy-lime-bullfrog
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-black-squirrel.sh
        container: qc.ver_whiny-mauve-eleuth
timeout: 1800
