config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: change-doc
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-orchid-snail.sh
        container: qc.acc_slimy-ultramarine-ostrich
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-taupe-hippopotamus.sh
        container: qc.doc_wheezy-lavender-reindeer
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-green-pig.sh
        container: qc.doc_goopy-brass-serval
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-zucchini-guppy.sh
        container: qc.doc_cozy-salmon-pig
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-turquoise-oriole.sh
        container: qc.lic_whiny-heliotrope-wallaby
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-lime-hyrax.sh
        container: qc.sec_tasty-russet-alligator
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-yellow-crocodile.sh
        container: qc.sec_messy-ochre-rattlesnake
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-aquamarine-barb.sh
        container: qc.sty_scanty-aqua-akita
      github.com/grycap/oscar hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-aqua-wallaby.sh
        container: qc.sty_chewy-orchid-chihuahua
      github.com/grycap/oscar jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-lemon-akbash.sh
        container: qc.sty_ugly-buff-rabbit
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-black-russel.sh
        container: qc.sty_clammy-corn-mongoose
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-chartreuse-rattlesnake.sh
        container: qc.ver_gummy-apricot-macaque
timeout: 1800
