config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.2
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: master
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-silver-vulture.sh
        container: qc.acc_skanky-goldenrod-gibbon
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-magnolia-toucan.sh
        container: qc.doc_shaky-beige-gibbon
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-azure-eel.sh
        container: qc.doc_stealthy-chartreuse-burmese
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-heliotrope-dachsbracke.sh
        container: qc.doc_droopy-auburn-jellyfish
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-eggplant-monster.sh
        container: qc.lic_pokey-corn-squirt
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-emerald-neanderthal.sh
        container: qc.sec_paltry-malachite-shrew
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-sepia-wolf.sh
        container: qc.sec_greasy-lavender-spoonbill
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.homey-maroon-husky.sh
        container: qc.sty_thirsty-zucchini-frog
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-fuchsia-shrimp.sh
        container: qc.sty_ugly-tan-bullfrog
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-corn-frog.sh
        container: qc.ver_pasty-myrtle-echidna
timeout: 1800
