config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: change-doc
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-amber-donkey.sh
        container: qc.acc_tacky-amber-koala
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-ruby-cassowary.sh
        container: qc.doc_lumpy-ivory-schnauzer
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-black-crocodile.sh
        container: qc.doc_flimsy-lavender-hummingbird
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-indigo-chipmunk.sh
        container: qc.doc_cranky-plum-tuatara
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-pear-millipede.sh
        container: qc.lic_gimpy-champagne-bracke
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-wisteria-dunker.sh
        container: qc.sec_sickly-peach-hippopotamus
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-flax-russel.sh
        container: qc.sec_tacky-tan-sheepdog
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-bronze-lizard.sh
        container: qc.sty_lousy-myrtle-corgi
      github.com/grycap/oscar hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-red-baboon.sh
        container: qc.sty_seedy-zucchini-dingo
      github.com/grycap/oscar jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-tan-moorhen.sh
        container: qc.sty_geeky-violet-stingray
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-peach-foxhound.sh
        container: qc.sty_cozy-amethyst-quoll
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-platinum-chow.sh
        container: qc.ver_sickly-magenta-boar
timeout: 1800
