config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: master
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-harlequin-numbat.sh
        container: qc.acc_cranky-bistre-worm
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-corn-russel.sh
        container: qc.doc_boozy-myrtle-malamute
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-cornflower-llama.sh
        container: qc.doc_foggy-yellow-loon
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-lilac-bloodhound.sh
        container: qc.doc_stinky-orange-birman
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-silver-hedgehog.sh
        container: qc.lic_lanky-apricot-moose
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-wheat-quetzal.sh
        container: qc.sec_fuzzy-crimson-gharial
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-tan-seahorse.sh
        container: qc.sec_crabby-alizarin-panda
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-taupe-kingfisher.sh
        container: qc.sty_cozy-myrtle-dalmatian
      github.com/grycap/oscar hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-plum-bandicoot.sh
        container: qc.sty_seedy-maroon-woodpecker
      github.com/grycap/oscar jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-wheat-moose.sh
        container: qc.sty_bumpy-cinnabar-seal
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-silver-macaw.sh
        container: qc.sty_hazy-ultramarine-sponge
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-champagne-zorse.sh
        container: qc.ver_sleepy-ruby-gar
timeout: 1800
