config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: change-doc
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-viridian-octopus.sh
        container: qc.acc_sleazy-celadon-uakari
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-coral-kiwi.sh
        container: qc.doc_skinny-linen-macaw
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-plum-horse.sh
        container: qc.doc_sloppy-orchid-dolphin
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.beady-eggplant-malamute.sh
        container: qc.doc_clammy-charcoal-discus
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-taupe-sheep.sh
        container: qc.lic_shaggy-salmon-balinese
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-cerise-cuscus.sh
        container: qc.sec_cozy-viridian-balinese
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.silly-dandelion-gerbil.sh
        container: qc.sec_leaky-asparagus-hamster
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-denim-starfish.sh
        container: qc.sty_snoopy-cinnamon-cougar
      github.com/grycap/oscar hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-indigo-stoat.sh
        container: qc.sty_crabby-sapphire-lionfish
      github.com/grycap/oscar jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-copper-clam.sh
        container: qc.sty_cloudy-harlequin-jellyfish
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-brown-chow.sh
        container: qc.sty_trippy-ivory-angelfish
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-pumpkin-wasp.sh
        container: qc.ver_stinky-salmon-hedgehog
timeout: 1800
