config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.6
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: change-doc
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-aqua-barb.sh
        container: qc.acc_grumpy-myrtle-mammoth
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-gold-squirt.sh
        container: qc.doc_silly-mustard-coati
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-mustard-wolverine.sh
        container: qc.doc_snappy-chocolate-quoll
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-buff-woodlouse.sh
        container: qc.doc_stuffy-orange-lion
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-azure-mandrill.sh
        container: qc.lic_leaky-ochre-eleuth
  QC.Met:
    repos:
      github.com/grycap/oscar validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-chestnut-uakari.sh
        container: qc.met_homely-lilac-spoonbill
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-platinum-zebra.sh
        container: qc.sec_boozy-denim-grouse
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-heliotrope-dachsbracke.sh
        container: qc.sec_shaky-brass-lobster
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-periwinkle-bonobo.sh
        container: qc.sty_slimy-maroon-chinchilla
      github.com/grycap/oscar hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-tomato-rabbit.sh
        container: qc.sty_woolly-amaranth-kingfisher
      github.com/grycap/oscar jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-lemon-moorhen.sh
        container: qc.sty_foggy-linen-donkey
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-thistle-shrew.sh
        container: qc.sty_greasy-orchid-manatee
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-cornflower-discus.sh
        container: qc.ver_foggy-blue-loon
timeout: 1800
