config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: change-doc
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-beige-lemming.sh
        container: qc.acc_geeky-gold-crocodile
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-alizarin-moorhen.sh
        container: qc.doc_ugly-black-dugong
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-pink-heron.sh
        container: qc.doc_droopy-corn-gibbon
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-brown-foxhound.sh
        container: qc.doc_muzzy-sapphire-kakapo
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-magnolia-dingo.sh
        container: qc.lic_boozy-magnolia-squid
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-cinnamon-termite.sh
        container: qc.sec_breezy-cinnamon-wrasse
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-pumpkin-kiwi.sh
        container: qc.sec_gimpy-vermilion-crab
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.messy-dandelion-cheetah.sh
        container: qc.sty_sleazy-burgundy-moth
      github.com/grycap/oscar hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-purple-urchin.sh
        container: qc.sty_craggy-chestnut-pinscher
      github.com/grycap/oscar jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-khaki-mau.sh
        container: qc.sty_zippy-sapphire-vulture
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-cream-newfoundland.sh
        container: qc.sty_ugly-cyan-flounder
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-sapphire-skunk.sh
        container: qc.ver_whiny-lemon-grouse
timeout: 1800
