config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: master
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-black-greyhound.sh
        container: qc.acc_skanky-tomato-foxhound
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-carmine-jackal.sh
        container: qc.doc_sunny-wheat-capybara
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-periwinkle-barb.sh
        container: qc.doc_tasty-rose-bandicoot
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-cerulean-fish.sh
        container: qc.doc_pretty-rose-chow
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-amber-spitz.sh
        container: qc.lic_snippy-peach-cuscus
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-harlequin-spoonbill.sh
        container: qc.sec_wiggy-cerise-eagle
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-pumpkin-cattle.sh
        container: qc.sty_cheeky-brass-turtle
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.ready-amber-octopus.sh
        container: qc.ver_slimy-heliotrope-albatross
timeout: 1800
