config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/gosec
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: master
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-brown-capuchin.sh
        container: qc.acc_messy-platinum-woodpecker
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-linen-reindeer.sh
        container: qc.doc_ugly-firebrick-hippopotamus
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-amethyst-panda.sh
        container: qc.doc_gummy-blue-discus
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-pumpkin-kangaroo.sh
        container: qc.doc_lanky-lime-worm
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-chocolate-kangaroo.sh
        container: qc.lic_silly-carmine-kingfisher
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-corn-jellyfish.sh
        container: qc.sec_fuzzy-platinum-koala
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-lilac-crane.sh
        container: qc.sec_shaky-ochre-mole
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-cinnabar-penguin.sh
        container: qc.sty_queasy-chocolate-scorpion
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-magnolia-barb.sh
        container: qc.ver_gummy-denim-rattlesnake
timeout: 1800
