config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.6
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: change-doc
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-smalt-snail.sh
        container: qc.acc_dorky-mustard-deer
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-cyan-okapi.sh
        container: qc.doc_squeaky-scarlet-deer
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-beige-oriole.sh
        container: qc.doc_crabby-indigo-lemur
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.randy-saffron-bracke.sh
        container: qc.doc_gimpy-cornflower-civet
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-harlequin-saola.sh
        container: qc.lic_boozy-amber-balinese
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-crimson-whippet.sh
        container: qc.sec_skanky-charcoal-setter
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.beady-olive-numbat.sh
        container: qc.sec_squirrely-alizarin-dane
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-brass-axolotl.sh
        container: qc.sty_paltry-eggplant-clam
      github.com/grycap/oscar hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-rose-dugong.sh
        container: qc.sty_sloppy-orange-civet
      github.com/grycap/oscar jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-black-bullfrog.sh
        container: qc.sty_skimpy-turquoise-ant
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-chestnut-toucan.sh
        container: qc.sty_skimpy-chartreuse-ferret
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-smalt-otter.sh
        container: qc.ver_trippy-gamboge-oriole
timeout: 1800
