config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.6
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: change-doc
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-violet-ragdoll.sh
        container: qc.acc_leaky-wheat-dodo
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-alizarin-emu.sh
        container: qc.doc_woolly-chartreuse-leopard
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-dandelion-bird.sh
        container: qc.doc_hilly-malachite-duck
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-pumpkin-llama.sh
        container: qc.doc_woozy-aquamarine-elephant
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.ready-sangria-cichlid.sh
        container: qc.lic_homey-saffron-wolverine
  QC.Met:
    repos:
      github.com/grycap/oscar validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-amber-numbat.sh
        container: qc.met_beady-periwinkle-dhole
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-auburn-camel.sh
        container: qc.sec_tasty-aquamarine-ladybird
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-amethyst-mastiff.sh
        container: qc.sec_randy-taupe-tapir
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-celadon-mongrel.sh
        container: qc.sty_paltry-purple-anteater
      github.com/grycap/oscar hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-seashell-retriever.sh
        container: qc.sty_wheezy-apricot-russel
      github.com/grycap/oscar jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-chestnut-baboon.sh
        container: qc.sty_cheeky-scarlet-avocet
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-jade-hyena.sh
        container: qc.sty_stealthy-persimmon-stingray
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.beady-persimmon-toad.sh
        container: qc.ver_shaggy-wisteria-ferret
timeout: 1800
