config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.2
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: master
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-cobalt-penguin.sh
        container: qc.acc_paltry-fuchsia-bongo
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-salmon-zebu.sh
        container: qc.doc_slaphappy-razzmatazz-binturong
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-emerald-gerbil.sh
        container: qc.doc_paltry-olivine-hornet
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-khaki-emu.sh
        container: qc.doc_sunny-white-hedgehog
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-emerald-panda.sh
        container: qc.lic_frumpy-turquoise-bulldog
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-eggplant-toad.sh
        container: qc.sec_leaky-auburn-newfoundland
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-purple-fowl.sh
        container: qc.sec_sunny-pink-woodpecker
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-smalt-discus.sh
        container: qc.sty_stealthy-wheat-anteater
      github.com/grycap/oscar jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-crimson-avocet.sh
        container: qc.sty_scaly-chestnut-rattlesnake
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-tomato-vulture.sh
        container: qc.sty_cheeky-purple-dane
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-brown-uakari.sh
        container: qc.ver_lanky-khaki-lion
timeout: 1800
