config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.2
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: master
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-gamboge-wolf.sh
        container: qc.acc_gimpy-khaki-mayfly
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-blue-meerkat.sh
        container: qc.doc_gummy-crimson-neanderthal
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-ivory-spitz.sh
        container: qc.doc_lanky-olivine-wildebeest
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-green-hamster.sh
        container: qc.doc_gummy-heliotrope-eleuth
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-platinum-mongoose.sh
        container: qc.lic_sickly-mustard-dane
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-copper-spitz.sh
        container: qc.sec_surly-purple-markhor
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-corn-greyhound.sh
        container: qc.sec_sleepy-wheat-manatee
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-razzmatazz-whippet.sh
        container: qc.sty_dorky-pumpkin-bonobo
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.surly-pumpkin-cattle.sh
        container: qc.sty_frumpy-green-russel
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-myrtle-moose.sh
        container: qc.ver_paltry-razzmatazz-opossum
timeout: 1800
