config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.2
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: master
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-cerise-sponge.sh
        container: qc.acc_shaky-chestnut-dhole
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.silly-burgundy-bulldog.sh
        container: qc.doc_gloppy-celadon-weasel
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-olivine-meerkat.sh
        container: qc.doc_zippy-cinnamon-oyster
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-cinnamon-birman.sh
        container: qc.doc_baggy-orchid-orangutan
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-chestnut-angora.sh
        container: qc.lic_thirsty-blue-earwig
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-taupe-dingo.sh
        container: qc.sec_snoopy-ochre-bee
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-brass-crab.sh
        container: qc.sec_trippy-myrtle-beagle
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-taupe-albatross.sh
        container: qc.sty_pokey-taupe-numbat
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-corn-wolfhound.sh
        container: qc.sty_paltry-seashell-stoat
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.homey-orchid-squid.sh
        container: qc.ver_gummy-black-dog
timeout: 1800
