config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: master
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-ultramarine-harrier.sh
        container: qc.acc_dorky-orchid-wildebeest
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-jade-hedgehog.sh
        container: qc.doc_bumpy-eggplant-budgerigar
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-rust-catfish.sh
        container: qc.doc_trippy-bronze-buffalo
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-heliotrope-tarsier.sh
        container: qc.doc_crappy-amethyst-macaque
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-brass-flamingo.sh
        container: qc.lic_surly-viridian-binturong
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-dandelion-sheepdog.sh
        container: qc.sec_shaky-alizarin-robin
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-aquamarine-termite.sh
        container: qc.sec_muggy-persimmon-discus
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-brass-wrasse.sh
        container: qc.sty_squeaky-malachite-panda
      github.com/grycap/oscar hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-green-serval.sh
        container: qc.sty_lousy-crimson-ostrich
      github.com/grycap/oscar jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-pumpkin-flamingo.sh
        container: qc.sty_stuffy-brown-tuatara
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-crimson-newfoundland.sh
        container: qc.sty_queasy-pumpkin-penguin
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-magenta-mastiff.sh
        container: qc.ver_tasty-linen-gorilla
timeout: 1800
