config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.2
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: master
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-brown-starfish.sh
        container: qc.acc_skimpy-asparagus-bombay
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-pink-hornet.sh
        container: qc.doc_flabby-azure-moose
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.homey-olive-elephant.sh
        container: qc.doc_wimpy-salmon-bee
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-khaki-hyena.sh
        container: qc.doc_pokey-chestnut-meerkat
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-russet-zonkey.sh
        container: qc.lic_homely-thistle-grouse
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-coral-macaw.sh
        container: qc.sec_skanky-ochre-dogfish
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-corn-dragonfly.sh
        container: qc.sec_whiny-firebrick-squirrel
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-cerise-chin.sh
        container: qc.sty_jumpy-buff-grasshopper
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-charcoal-mastiff.sh
        container: qc.sty_cloudy-ruby-bombay
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-green-wildebeest.sh
        container: qc.ver_flabby-goldenrod-toad
timeout: 1800
