config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/gosec
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: master
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-denim-dachshund.sh
        container: qc.acc_dorky-pumpkin-barb
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-russet-catfish.sh
        container: qc.doc_craggy-russet-coyote
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-blue-hamster.sh
        container: qc.doc_pokey-cardinal-oyster
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-purple-antelope.sh
        container: qc.doc_nippy-malachite-elephant
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-tan-horse.sh
        container: qc.lic_gummy-pumpkin-llama
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.silly-cerise-earwig.sh
        container: qc.sec_freaky-blue-beetle
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-aqua-fox.sh
        container: qc.sec_sleepy-heliotrope-heron
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-bronze-dollar.sh
        container: qc.sty_leaky-fuchsia-opossum
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-brown-discus.sh
        container: qc.ver_gamy-beige-shrew
timeout: 1800
