config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: change-doc
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-black-neanderthal.sh
        container: qc.acc_shaggy-sangria-mammoth
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-ecru-schnauzer.sh
        container: qc.doc_leaky-bistre-avocet
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-cornflower-wombat.sh
        container: qc.doc_wheezy-buff-cheetah
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.randy-olive-octopus.sh
        container: qc.doc_ready-maroon-seahorse
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-cobalt-baboon.sh
        container: qc.lic_smelly-cardinal-eel
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-orchid-uakari.sh
        container: qc.sec_sleepy-asparagus-wildebeest
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-burgundy-tapir.sh
        container: qc.sec_thirsty-red-cattle
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-ruby-devil.sh
        container: qc.sty_bluesy-sangria-neanderthal
      github.com/grycap/oscar hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-zucchini-caiman.sh
        container: qc.sty_hasty-viridian-yak
      github.com/grycap/oscar jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-dandelion-ostrich.sh
        container: qc.sty_surly-cornflower-macaw
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-sangria-elephant.sh
        container: qc.sty_sickly-lemon-cat
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-chartreuse-coral.sh
        container: qc.ver_lanky-olivine-lynx
timeout: 1800
