config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: master
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-orange-mau.sh
        container: qc.acc_snippy-indigo-caterpillar
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-indigo-tapir.sh
        container: qc.doc_flimsy-sepia-baboon
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.beady-chartreuse-chameleon.sh
        container: qc.doc_lanky-carmine-budgerigar
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-cream-dollar.sh
        container: qc.doc_clammy-persimmon-budgerigar
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-razzmatazz-beaver.sh
        container: qc.lic_seedy-khaki-salamander
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-green-mist.sh
        container: qc.sec_foggy-ultramarine-cat
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-brown-abyssinian.sh
        container: qc.sty_homey-salmon-cattle
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-corn-spider.sh
        container: qc.ver_shaggy-coral-balinese
timeout: 1800
