config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.2
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: master
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-black-emu.sh
        container: qc.acc_thirsty-yellow-tuatara
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.homey-champagne-rat.sh
        container: qc.doc_hilly-pear-manatee
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-apricot-olm.sh
        container: qc.doc_wiggy-olivine-dragon
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-rust-toad.sh
        container: qc.doc_smelly-taupe-mist
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-vermilion-binturong.sh
        container: qc.lic_nippy-puce-wildebeest
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-apricot-monster.sh
        container: qc.sec_craggy-carmine-fish
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-crimson-argentino.sh
        container: qc.sec_stinky-smalt-beetle
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.homey-bistre-otter.sh
        container: qc.sty_wiggy-cerulean-wolf
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-ochre-reindeer.sh
        container: qc.sty_pasty-tangerine-kiwi
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-lilac-emu.sh
        container: qc.ver_surly-emerald-macaw
timeout: 1800
