config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.2
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: master
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-asparagus-cat.sh
        container: qc.acc_craggy-lavender-burmese
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-sapphire-quetzal.sh
        container: qc.doc_muggy-azure-pig
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-violet-eleuth.sh
        container: qc.doc_dorky-sangria-gerbil
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-plum-blue.sh
        container: qc.doc_skinny-eggplant-moose
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-coral-angora.sh
        container: qc.lic_homey-rust-flounder
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-puce-bonobo.sh
        container: qc.sec_randy-coral-dachshund
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.homely-asparagus-reindeer.sh
        container: qc.sec_crappy-asparagus-donkey
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-cobalt-chamois.sh
        container: qc.sty_skanky-asparagus-woodpecker
      github.com/grycap/oscar jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.silly-plum-orangutan.sh
        container: qc.sty_gimpy-brass-hyena
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-heliotrope-cat.sh
        container: qc.sty_seedy-harlequin-fox
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-periwinkle-starfish.sh
        container: qc.ver_skanky-olive-insect
timeout: 1800
