config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.6
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: change-doc
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-mustard-ostrich.sh
        container: qc.acc_snazzy-alizarin-mayfly
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-bistre-mammoth.sh
        container: qc.doc_foggy-wheat-crane
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.silly-chocolate-fousek.sh
        container: qc.doc_blurry-goldenrod-meerkat
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-heliotrope-loon.sh
        container: qc.doc_randy-tan-dugong
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-asparagus-ant.sh
        container: qc.lic_shaky-russet-falcon
  QC.Met:
    repos:
      github.com/grycap/oscar validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-crimson-wallaby.sh
        container: qc.met_paltry-tan-wombat
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-ultramarine-whippet.sh
        container: qc.sec_squirrely-peach-fish
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-indigo-chicken.sh
        container: qc.sec_gamy-firebrick-seahorse
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.surly-ivory-dodo.sh
        container: qc.sty_woozy-purple-centipede
      github.com/grycap/oscar hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-jade-quail.sh
        container: qc.sty_lumpy-viridian-chinchilla
      github.com/grycap/oscar jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-black-schnauzer.sh
        container: qc.sty_shaggy-olivine-heron
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-cinnamon-bobcat.sh
        container: qc.sty_ugly-myrtle-sponge
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.surly-azure-foxhound.sh
        container: qc.ver_flabby-cardinal-nightingale
timeout: 1800
