config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: master
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-wheat-quoll.sh
        container: qc.acc_cloudy-orange-oriole
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-lime-echidna.sh
        container: qc.doc_sleazy-aquamarine-kangaroo
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-brass-lobster.sh
        container: qc.doc_squirrely-mustard-squirrel
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-burgundy-eel.sh
        container: qc.doc_chewy-beige-weasel
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-russet-robin.sh
        container: qc.lic_homey-beige-liger
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-tomato-mandrill.sh
        container: qc.sec_boozy-denim-capuchin
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-rust-jackal.sh
        container: qc.sec_queasy-gold-jellyfish
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-gamboge-cat.sh
        container: qc.sty_cloudy-indigo-moose
      github.com/grycap/oscar hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.beady-flax-alligator.sh
        container: qc.sty_freaky-malachite-chow
      github.com/grycap/oscar jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.homely-puce-dragon.sh
        container: qc.sty_greasy-aquamarine-quetzal
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-cream-akbash.sh
        container: qc.sty_snoopy-yellow-gar
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-ivory-tarantula.sh
        container: qc.ver_stuffy-pink-gecko
timeout: 1800
