config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: change-doc
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.messy-malachite-moose.sh
        container: qc.acc_randy-seashell-albatross
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-sangria-tarsier.sh
        container: qc.doc_slimy-saffron-hedgehog
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-amethyst-scorpion.sh
        container: qc.doc_queasy-saffron-magpie
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-wisteria-millipede.sh
        container: qc.doc_leaky-brown-mandrill
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-sepia-leopard.sh
        container: qc.lic_crappy-indigo-guppy
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-pumpkin-saola.sh
        container: qc.sec_shaggy-beige-labradoodle
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-eggplant-tuatara.sh
        container: qc.sec_ready-crimson-chameleon
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-bistre-crane.sh
        container: qc.sty_nippy-mauve-dugong
      github.com/grycap/oscar hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-flax-burmese.sh
        container: qc.sty_randy-burgundy-newt
      github.com/grycap/oscar jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-ivory-dragon.sh
        container: qc.sty_pokey-brown-cheetah
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-heliotrope-dormouse.sh
        container: qc.sty_lumpy-amber-cassowary
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-puce-lionfish.sh
        container: qc.ver_foggy-olive-abyssinian
timeout: 1800
